# 添加新型号教程 https://www.wunote.cn/article/2307/
# IPQ40XX 适配 142ac 代码 https://github.com/Lienol/openwrt
# ACRH17（）适配OPENWRT https://leux.cc/doc/ACRH17%E9%80%82%E9%85%8DOPENWRT.html
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2020 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# https://github.com/hackyes/OpenWrt-CI

name: Raisecom_MSG230-ACN-XDI
#  Raisecom_MSG230-ACN-XDI QCA9531+QCA9887，16M+128M
on:
  push:
    branches: 
      - master
  schedule:
    - cron: 0 0 1 * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -yqq update
          sudo -E apt-get -yqq install  build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc-s1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
      - name: Download Openwrt
        run: |
          
          #git clone https://github.com/openwrt/openwrt/tree/v22.03.2
          wget https://github.com/openwrt/openwrt/archive/refs/tags/v22.03.4.tar.gz
          tar -zxvf v22.03.4.tar.gz
          
          #先删除最后一行的 uci commit
          sed -i "s/uci commit//" /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "uci -q batch <<-EOF" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          #设置时区
          echo "	set system.@system[-1].zonename='Asia/Shanghai'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set system.@system[-1].timezone='CST-8'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate

          #设置 NTP 对时服务器、DNS 服务器
          echo "	delete system.ntp.server" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	add_list system.ntp.server='ntp1.aliyun.com'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	add_list system.ntp.server='time2.cloud.tencent.com'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set network.lan.dns='223.6.6.6'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	add_list network.lan.dns='180.76.76.76'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          
          #设置 Run LED 默认闪烁
          echo "	set system.Run_Led='led'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set system.Run_Led.name='Run_Led'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set system.Run_Led.sysfs='white:system'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set system.Run_Led.trigger='timer'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set system.Run_Led.delayon='750'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set system.Run_Led.delatyoff='750'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          
          #修改重置时闪灯
          #sed -i "s/green:system/white:system/" /home/runner/work/OpenWrt/OpenWrt/package/base-files/files/etc/rc.button/reset
          
          #初始化防火墙配置，启用硬件转发
          echo "	set firewall.@defaults[-1].flow_offloading='1'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          echo "	set firewall.@defaults[-1].flow_offloading_hw='1'" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          
          echo "EOF" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          
          #应用设置
          echo "uci commit" >> /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package/base-files/files/bin/config_generate
          
          cp -r /home/runner/work/OpenWrt/OpenWrt/target/* /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/target
          cp -r /home/runner/work/OpenWrt/OpenWrt/package/* /home/runner/work/OpenWrt/OpenWrt/openwrt-22.03.4/package
          
          rm -rf target
          rm -rf package
          rm -rf build_dir
          cp .config ./openwrt-22.03.4
          mv ./openwrt-22.03.4/* ./
          #修改 root 密码为 GL-FE-AProot
          #sed -i 's/root::0:0:99999:7:::/root:$1$k4M.ZHV1$rzEKCtrJEYPr0qwH..pzl\/:19103:0:99999:7:::/' ./package/base-files/files/etc/shadow
      #- name: Install Helloword
        #run: |
          #echo "src-git helloworld https://github.com/fw876/helloworld" >> ./feeds.conf.default 
      #- name: Install OpenClash
        #run: |
          #mkdir package/luci-app-openclash
          #cd package/luci-app-openclash
          #git init
          #git remote add -f origin https://github.com/vernesong/OpenClash.git
          #git config core.sparsecheckout true
          #echo "luci-app-openclash" >> .git/info/sparse-checkout
          #git pull --depth 1 origin master
          #git branch --set-upstream-to=origin/master master
          #pushd luci-app-openclash/tools/po2lmo
          #make && sudo make install
          #popd
      - name: Update feeds
        run: |
          cat /home/runner/work/OpenWrt/OpenWrt/package/base-files/files/bin/config_generate
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          #在 Luci 语言选择项上加上中文
          sed -i "s/config internal languages/config internal languages\n\toption zh_cn \'Chinese zh-cn\'/" ./feeds/luci/modules/luci-base/root/etc/config/luci
          #默认为英文
          sed -i "s/option lang auto/option lang en/" ./feeds/luci/modules/luci-base/root/etc/config/luci
          cat ./feeds/luci/modules/luci-base/root/etc/config/luci
      - name: Costom configure file
        run: |
          rm .config
          mv Raisecom_MSG230-ACN-XDI.config .config
          #echo aaaaaa
          #cat .config
          #echo aaaaaa
          make defconfig
          #cat .config
          #echo aaaaaa
      - name: Download package source code
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;
      - name: Compile firmware
        run: |
          echo -e "$(nproc) thread build."
          make -j$(nproc) V=s
          #make -j$(nproc) V=s
      - name : Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt_firmware
          path: bin/targets/
